# This file is auto-generated by goreleaser. Do not edit manually.
class Apkhub < Formula
  desc "A command-line tool for managing distributed APK repositories"
  homepage "https://github.com/huanfeng/apkhub"
  version "0.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/huanfeng/apkhub/releases/download/v#{version}/apkhub-#{version}-darwin-arm64.tar.gz"
      sha256 "REPLACE_ME"
    else
      url "https://github.com/huanfeng/apkhub/releases/download/v#{version}/apkhub-#{version}-darwin-x86_64.tar.gz"
      sha256 "REPLACE_ME"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/huanfeng/apkhub/releases/download/v#{version}/apkhub-#{version}-linux-arm64.tar.gz"
      sha256 "REPLACE_ME"
    else
      url "https://github.com/huanfeng/apkhub/releases/download/v#{version}/apkhub-#{version}-linux-x86_64.tar.gz"
      sha256 "REPLACE_ME"
    end
  end

  def install
    bin.install "apkhub"
  end

  test do
    system "#{bin}/apkhub", "version"
  end
end
